type Track={name:string,learn:string,practice:string};
const tracks:Track[]=[
{name:'AI Basics for Beginners',learn:'AI concepts, machine learning basics, generative AI, responsible use, privacy and verification.',practice:'Use non-sensitive examples and manually verify important outputs.'},
{name:'Prompting & Verification',learn:'Instructions, context, constraints, structured outputs, assumptions, source checking and hallucination control.',practice:'Compare AI answers against primary or authoritative sources.'},
{name:'AI for Office & Productivity',learn:'Documents, spreadsheets, presentations, research support and safe workflow assistance.',practice:'Use dummy data to complete one real-style task and quality-check it manually.'},
{name:'AI for Small Business',learn:'Research support, catalogue drafts, marketing ideas, FAQ drafts, operations and scenario planning.',practice:'Create one business asset and test whether it genuinely saves time or improves clarity.'},
{name:'AI for Social Media & Creators',learn:'Ideation, scripts, captions, visuals, video assistance, localisation and analytics interpretation.',practice:'Create original content while recording the source/licence of every asset.'},
{name:'AI Image, Animation & Video',learn:'Storyboarding, image/video generation, animation workflow, editing, voice/audio and provenance.',practice:'Produce a short original clip using only assets you created or can commercially use.'},
{name:'AI for Teachers & Tutors',learn:'Lesson planning, examples, quizzes, differentiation and responsible educational use.',practice:'Create a lesson aid, then verify accuracy, learner level and privacy.'},
{name:'AI for Data & Spreadsheets',learn:'Data preparation, formulas, analysis assistance, cleaning and validation.',practice:'Test AI-suggested calculations on a small dataset with known answers.'},
{name:'AI Coding Foundations',learn:'Programming fundamentals, code assistance, debugging, testing, security and version control.',practice:'Build a tiny project and test generated code rather than copying it blindly.'},
{name:'AI Automation / No-code',learn:'Workflow mapping, triggers, actions, APIs, permissions, failures and human review.',practice:'Automate a harmless repetitive task and deliberately test failure cases.'},
{name:'AI Translation & Indian Languages',learn:'Translation, transliteration, terminology, speech/text workflows and human review.',practice:'Translate a non-sensitive sample and check names, numbers, meaning and tone manually.'},
{name:'AI Safety, Privacy & Copyright',learn:'Sensitive data, hallucinations, deepfakes, consent, copyright, licensing and provenance.',practice:'Audit an AI workflow for data, factual and rights risks before publishing.'}
];
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
function renderAiLearning(){const a=document.querySelector<HTMLDivElement>('#app');if(!a)return;a.innerHTML=`<main class="shell"><header><p class="eyebrow">LEARN & GROW · AI</p><h1>Practical AI learning paths</h1><p>Learn a useful skill, practise it, verify the output and build proof of work. A course or certificate does not guarantee employment or income.</p></header><article class="card dropdown-panel"><label>Choose AI direction<select id="ai-track"><option value="">Choose from ${tracks.length} paths</option>${tracks.map((x,i)=>`<option value="${i}">${esc(x.name)}</option>`).join('')}</select></label><button class="choice" id="ai-open" type="button">Show learning path<span>›</span></button></article><article class="card"><h2>Verified India learning routes</h2><p><a href="https://swayam.gov.in/search_courses" target="_blank" rel="noopener noreferrer">SWAYAM — search current AI courses</a></p><p><a href="https://swayamplus.education.gov.in/courses/introduction-to-artificial-intelligence-ai" target="_blank" rel="noopener noreferrer">SWAYAM Plus — Fundamentals of Artificial Intelligence</a></p><p>SWAYAM is a Ministry of Education initiative. Its current catalogue includes multiple AI courses; course dates and enrollment windows change, so verify the current listing before enrolling.</p></article><button class="choice" id="ai-future" type="button">Explore near-future career directions<span>›</span></button><nav class="nav"><button id="ai-back" type="button">← Back</button><button id="ai-home" type="button">Home</button></nav></main>`;}
function detail(i:number){const r=tracks[i],a=document.querySelector<HTMLDivElement>('#app');if(!r||!a)return;a.innerHTML=`<main class="shell"><header><p class="eyebrow">AI LEARNING PATH</p><h1>${esc(r.name)}</h1></header><article class="card needs-panel"><p><strong>Learn:</strong> ${esc(r.learn)}</p><p><strong>Practice:</strong> ${esc(r.practice)}</p><p><strong>Proof:</strong> save one useful project/sample that demonstrates your own contribution without private or unlicensed material.</p></article><article class="card"><p class="caution"><strong>COURSE CHECK:</strong> verify syllabus, prerequisites, language, provider, fees, certificate terms and last-updated date before enrolling. AI tools change quickly.</p></article><nav class="nav"><button id="ai-detail-back" type="button">← Back</button><button id="ai-home" type="button">Home</button></nav></main>`;}
document.addEventListener('click',e=>{const t=e.target as HTMLElement;if(t.closest('#ai-open')){const v=document.querySelector<HTMLSelectElement>('#ai-track')?.value;if(v!==undefined&&v!=='')detail(Number(v));return;}if(t.closest('#ai-detail-back')){renderAiLearning();return;}if(t.closest('#ai-future')){document.dispatchEvent(new Event('open-future-careers'));return;}if(t.closest('#ai-back')){document.dispatchEvent(new Event('open-learn'));return;}if(t.closest('#ai-home'))location.href='/';});
document.addEventListener('open-ai-learning',renderAiLearning);
export {tracks,renderAiLearning};