const app=()=>document.querySelector<HTMLDivElement>('#app');
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const types=['Shop / Retail','Service / Skill','Farmer / Agriculture','Home-based','Manufacturing','Digital / Online','Other'];
const signals=[
['sales','Sales / income trend',['Growing','Stable','Falling','Too irregular to tell']],
['customers','Customer / enquiry trend',['Growing','Stable','Falling','Not tracked']],
['margin','Margin after direct costs',['Healthy','Tight','Negative / loss','Not calculated']],
['repeat','Repeat customers',['Strong','Some','Low','Not tracked']],
['competition','Competition pressure',['Low','Moderate','High','Not sure']],
['marketing','Marketing effectiveness',['Working well','Some response','Weak response','Not measured']],
['stock','Inventory / capacity',['Healthy','Too much unused stock/capacity','Too little capacity / shortages','Not applicable / not tracked']],
['cash','Cash-flow pressure',['Low','Manageable','High','Not tracked']],
['digital','Digital presence',['Strong','Basic','Weak / none','Not relevant']],
['operations','Operational consistency',['Reliable','Some delays/rework','Frequent problems','Not tracked']]
] as const;
let selectedType=types[0]; const state:Record<string,string>={};
const nav=()=>'<nav class="nav"><button id="ba-back">← Back</button><button id="ba-home">Home</button></nav>';

function home(){const a=app();if(!a)return;a.innerHTML=`<main class="shell"><header><p class="eyebrow">Business Analysis</p><h1>Analyse my dhandha</h1><p>Find the business gap before spending more money.</p></header><article class="card dropdown-panel"><label>Business type<select id="ba-type">${types.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><button class="choice" id="ba-start">Start analysis<span>›</span></button></article><article class="card"><h2>What this checks</h2><p>Sales, customers, margins, repeat business, competition, marketing, inventory/capacity, cash flow, digital presence and operations.</p><p><strong>Privacy:</strong> no account or personal identity details are needed.</p></article>${nav()}</main>`;a.querySelector('#ba-start')?.addEventListener('click',()=>{selectedType=a.querySelector<HTMLSelectElement>('#ba-type')?.value||types[0];questions();});a.querySelector('#ba-back')?.addEventListener('click',()=>location.href='/');a.querySelector('#ba-home')?.addEventListener('click',()=>location.href='/');}
function questions(){const a=app();if(!a)return;a.innerHTML=`<main class="shell"><header><p class="eyebrow">Business Analysis · ${esc(selectedType)}</p><h1>Business signals</h1><p>Choose the closest current condition. “Not tracked” is valid.</p></header><form class="card calculator-panel">${signals.map(([k,l,o])=>`<label>${esc(l)}<select data-ba="${k}">${o.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label>`).join('')}</form><button class="choice" id="ba-analyse">Find my business gaps<span>›</span></button>${nav()}</main>`;a.querySelector('#ba-analyse')?.addEventListener('click',()=>{for(const [k] of signals)state[k]=a.querySelector<HTMLSelectElement>(`[data-ba="${k}"]`)?.value||'';result();});a.querySelector('#ba-back')?.addEventListener('click',home);a.querySelector('#ba-home')?.addEventListener('click',()=>location.href='/');}
function gaps(){const g:{area:string;next:string}[]=[];const add=(area:string,next:string)=>g.push({area,next});if(/Falling|irregular/i.test(state.sales))add('Sales','Separate demand, pricing, customer-count and average-order-value causes.');if(/Falling|Not tracked/i.test(state.customers))add('Customer flow','Track enquiries, conversions and repeat customers by channel.');if(/Tight|Negative|Not calculated/i.test(state.margin))add('Margin','Use Paisa Check to separate price, direct costs and fixed costs.');if(/Low|Not tracked/i.test(state.repeat))add('Retention','Track repeat rate, complaints and service quality.');if(/High|Not sure/i.test(state.competition))add('Competition','Compare price, quality, convenience, trust, speed and digital discovery.');if(/Weak response|Not measured/i.test(state.marketing))add('Marketing','Track genuine enquiries and conversions, not follower count alone.');if(/Too much|Too little|Not applicable/i.test(state.stock))add('Inventory / capacity','Measure stock turns, utilisation, shortages, wastage and working capital.');if(/High|Not tracked/i.test(state.cash))add('Cash flow','Map cash timing, receivables, inventory lock-up and fixed commitments.');if(/Weak|Basic/i.test(state.digital))add('Digital discovery','Improve accurate listings, catalogue/portfolio, contact clarity and proof.');if(/delays|Frequent|Not tracked/i.test(state.operations))add('Operations','Track delays, rework, complaints, wastage and bottlenecks.');return g;}
function result(){const a=app();if(!a)return;const g=gaps();const rows=g.length?g:[{area:'Measurement',next:'No major warning surfaced from these broad answers. Validate with real numbers before assuming the business is healthy.'}];a.innerHTML=`<main class="shell"><header><p class="eyebrow">Business Analysis · GUIDANCE</p><h1>Gap map</h1><p>Structured diagnostic, not a score or guarantee.</p></header><div class="table-wrap"><table><thead><tr><th>Gap area</th><th>Next check</th></tr></thead><tbody>${rows.map(x=>`<tr><th>${esc(x.area)}</th><td>${esc(x.next)}</td></tr>`).join('')}</tbody></table></div><article class="card research-panel"><h2>Market research before action</h2><p>For the exact business, product or service, check current market share/size where meaningful, future predicted share/size and forecast horizon, sourced CAGR, growth perspective and competition. If India-specific evidence is unavailable, mark it not verified rather than inventing precision.</p></article><article class="card"><h2>30 / 60 / 90-day improvement frame</h2><ol><li><strong>30 days:</strong> measure weak signals and stop obvious leakage.</li><li><strong>60 days:</strong> test one pricing, marketing, product, service or process improvement at a time.</li><li><strong>90 days:</strong> compare results against the baseline and keep only changes that improve real outcomes.</li></ol></article><button class="choice" id="ba-paisa">Open Paisa Check<span>›</span></button><button class="choice" id="ba-restart">Analyse again<span>›</span></button>${nav()}</main>`;a.querySelector('#ba-paisa')?.addEventListener('click',()=>document.dispatchEvent(new Event('open-paisa-business')));a.querySelector('#ba-restart')?.addEventListener('click',home);a.querySelector('#ba-back')?.addEventListener('click',questions);a.querySelector('#ba-home')?.addEventListener('click',()=>location.href='/');}
document.addEventListener('open-business-analysis',home);
export {home as openBusinessAnalysis};
