type Career={name:string,why:string,skills:string,ai:string};
const careers:Career[]=[
{name:'AI / Machine Learning Specialist',why:'Technology-intensive role family with strong current demand signals and continued adoption across sectors.',skills:'Python, statistics, machine learning, data, evaluation, deployment and responsible AI.',ai:'Start with foundations, then Python/ML and small verified projects.'},
{name:'Big Data / Data Engineering',why:'Data infrastructure remains important as organisations collect and operationalise larger datasets.',skills:'SQL, data modelling, pipelines, cloud data tools, quality and governance.',ai:'Use AI for assistance, but validate data logic, lineage and outputs.'},
{name:'Cybersecurity',why:'Security demand grows as digital systems, cloud services and AI adoption expand attack surfaces.',skills:'Networks, operating systems, identity, secure configuration, monitoring and incident response.',ai:'Learn defensive workflows and safe lab practice; do not rely on AI output without verification.'},
{name:'Software / Application Development',why:'Software remains a broad foundation across consumer, business and public-sector systems.',skills:'Programming, APIs, databases, testing, security and version control.',ai:'Use coding assistants as accelerators, not substitutes for testing and understanding.'},
{name:'FinTech / Digital Finance Technology',why:'Digital payments, financial infrastructure and compliance technology continue to create specialised technical roles.',skills:'Software/data, payments concepts, security, regulation awareness and product thinking.',ai:'Keep financial/regulatory claims within verified scope and current rules.'},
{name:'Cloud / DevOps / Platform Engineering',why:'Modern applications increasingly depend on cloud infrastructure, automation and reliable deployment.',skills:'Linux, networking, cloud services, containers, CI/CD, observability and security.',ai:'Use AI for troubleshooting support while protecting credentials and production secrets.'},
{name:'AI Product / Automation Specialist',why:'Businesses increasingly need people who can redesign workflows around AI and automation.',skills:'Process mapping, prompting, APIs, no-code/low-code, testing, human review and ROI measurement.',ai:'Focus on useful workflows, privacy and failure handling rather than novelty.'},
{name:'Robotics / Industrial Automation',why:'Manufacturing, warehousing and service operations continue adding automation and sensor-driven systems.',skills:'Electronics, mechanics, controls, programming, safety and maintenance.',ai:'Combine AI with physical-system safety and deterministic controls.'},
{name:'Semiconductor / Electronics Engineering',why:'Electronics and semiconductor ecosystems remain strategically important across devices, vehicles and infrastructure.',skills:'Electronics, embedded systems, verification, manufacturing/process knowledge and quality.',ai:'Use AI as an engineering aid; hardware validation remains essential.'},
{name:'Renewable Energy / Energy Systems',why:'Energy transition creates work across solar, storage, grid integration, efficiency and operations.',skills:'Electrical/energy fundamentals, design, safety, project execution, maintenance and regulation awareness.',ai:'Use current technical standards and official energy guidance for real projects.'},
{name:'Climate Finance Specialist / Green Project Finance Analyst',why:'Decarbonisation projects create demand for professionals who can understand project economics, climate frameworks and financing structures.',skills:'Financial modelling, project finance, climate/energy literacy, due diligence, documentation and regulatory awareness.',ai:'Keep to analysis/support unless appropriately licensed; do not provide regulated investment or lending advice without authority.'},
{name:'Healthcare + AI / Health Data',why:'Healthcare digitisation and AI-assisted workflows create roles spanning clinical operations, analytics and software.',skills:'Domain knowledge, data, privacy, validation, safety and workflow design.',ai:'High-stakes outputs require professional oversight and rigorous validation.'},
{name:'AI-enabled Educator / Trainer',why:'Teaching increasingly uses digital and AI tools while still requiring strong subject and facilitation skills.',skills:'Subject expertise, instructional design, assessment, communication and responsible AI use.',ai:'Use AI to support learning materials while verifying accuracy and protecting learner privacy.'},
{name:'Digital Creator / Animation / Video',why:'Audience-led media and business content create independent and employed roles across languages and niches.',skills:'Scripting, editing, animation, design, rights management, analytics and audience development.',ai:'Keep provenance, originality and platform-policy checks for generated or assisted content.'},
{name:'Human + AI Domain Specialist',why:'Many industries need people who can combine domain expertise with AI-enabled workflows rather than pure AI research.',skills:'Strong domain knowledge, workflow design, verification, communication and responsible AI use.',ai:'Build proof around measurable domain outcomes, not generic tool usage.'}
];
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
function renderFutureCareers(){const a=document.querySelector<HTMLDivElement>('#app');if(!a)return;a.innerHTML=`<main class="shell"><header><p class="eyebrow">Future Career Directions</p><h1>Research strong-growth career areas</h1><p>These are directional areas to investigate, not a salary ranking, job guarantee or prediction of your personal outcome.</p></header><article class="card dropdown-panel"><label>Career direction<select id="future-career"><option value="">Choose from ${careers.length} directions</option>${careers.map((x,i)=>`<option value="${i}">${esc(x.name)}</option>`).join('')}</select></label><button class="choice" id="future-open">Needs & Requirements<span>›</span></button></article><article class="card research-panel"><h2>Evidence rule</h2><p>Compare current vacancies, required skills, qualification expectations, portfolio/proof, location and actual compensation evidence. This is not a salary ranking.</p></article><article class="card"><h2>Trusted learning routes</h2><a class="choice" href="https://swayam.gov.in/" target="_blank" rel="noopener noreferrer">SWAYAM<span>↗</span></a><a class="choice" href="https://www.futureskillsprime.in/" target="_blank" rel="noopener noreferrer">FutureSkills Prime<span>↗</span></a></article><nav class="nav"><button id="future-back">← Back</button><button id="future-home">Home</button></nav></main>`;}
let activeFutureIndex=-1;
function detail(i:number){activeFutureIndex=i;const a=document.querySelector<HTMLDivElement>('#app'),x=careers[i];if(!a||!x)return;a.innerHTML=`<main class="shell"><header><p class="eyebrow">Future Career Direction</p><h1>${esc(x.name)}</h1></header><article class="card needs-panel"><p><strong>Why research it:</strong> ${esc(x.why)}</p><p><strong>Skills:</strong> ${esc(x.skills)}</p><p><strong>AI / technology approach:</strong> ${esc(x.ai)}</p></article><article class="card research-panel" data-career-research><h2>${esc(x.name)} market research</h2><p>Research current India-specific market share or market size where meaningful, future predicted share or size with a stated forecast horizon, CAGR only from a compatible source and definition, growth perspective, direct and substitute competition, and major entry barriers.</p><p><strong>Evidence rule:</strong> if a reliable India-specific number is unavailable, show that it is not verified rather than inventing precision.</p></article><article class="card"><p><strong>Things to check before proceeding:</strong> current role descriptions, actual vacancies, required qualifications, location, experience level, portfolio expectations and compensation evidence. No job, salary or placement is guaranteed.</p></article><button class="choice" id="future-save" type="button">Save My Plan on this device<span>›</span></button><p id="future-save-status" role="status"></p><nav class="nav"><button id="future-detail-back">← Back</button><button id="future-home">Home</button></nav></main>`;}
document.addEventListener('click',e=>{const t=e.target as HTMLElement;if(t.closest('#future-open')){const v=document.querySelector<HTMLSelectElement>('#future-career')?.value;if(v)detail(Number(v));return;}if(t.closest('#future-save')){const x=careers[activeFutureIndex];if(x)localStorage.setItem('skill-aur-dhandha-path-choice',JSON.stringify({route:'Future Career Directions',choice:x.name,savedAt:new Date().toISOString()}));const s=document.querySelector<HTMLElement>('#future-save-status');if(s)s.textContent=x?'Plan saved locally on this device.':'Open a career direction before saving.';return;}if(t.closest('#future-detail-back')){renderFutureCareers();return;}if(t.closest('#future-back')){document.dispatchEvent(new Event('open-learn'));return;}if(t.closest('#future-home')){location.href='/';return;}});
document.addEventListener('open-future-careers',renderFutureCareers);
export {careers,renderFutureCareers};
