const govModes=['Business Support','Jobs & Skills','Farmer Support','MSME Support','Financial Benefits','Registrations/Approvals','Not Sure'] as const;
let govMode='Not Sure';
const gmic=()=>`<button class="mic" type="button" aria-label="Voice input"><span aria-hidden="true">●</span> Voice input</button>`;
const gnav=(id:string)=>`<nav class="nav" aria-label="Navigation"><button id="${id}" type="button">← Back</button><button id="gov-home" type="button">Home</button></nav>`;
const govRoot=()=>{location.href='/';};
type Route={name:string,url:string,note:string};
const routeMap:Record<string,Route[]>={
'Business Support':[
{name:'myScheme',url:'https://www.myscheme.gov.in/',note:'Government-scheme discovery route. Check the individual scheme page for current eligibility and application details.'},
{name:'National Single Window System',url:'https://www.nsws.gov.in/',note:'Identify and access participating business approvals. Treat its approval guidance as a starting point, not exhaustive legal clearance.'},
{name:'Udyam Registration',url:'https://udyamregistration.gov.in/',note:'Official Ministry of MSME registration portal. Udyam registration is free; avoid private sites claiming to be the official registration service.'}],
'Jobs & Skills':[
{name:'National Career Service',url:'https://www.ncs.gov.in/',note:'Official Ministry of Labour & Employment career and employment route. NCS states its services are free of cost; be alert to fraudulent fee requests.'},
{name:'NCS International Jobs / e-Migrate',url:'https://ncs.gov.in/e-migrate',note:'Official NCS route for international-job discovery. Verify employer, recruiter, contract, visa and migration requirements through official channels before acting.'},
{name:'Skill India Digital / DGT',url:'https://dgt.skillindiadigital.gov.in/',note:'Government skill-training route. Verify current course, provider, participation and certification details on the destination.'},
{name:'e-Shram',url:'https://eshram.gov.in/',note:'Official Ministry of Labour & Employment unorganised-worker portal. Check current registration scope and conditions there.'}],
'Farmer Support':[
{name:'myScheme',url:'https://www.myscheme.gov.in/',note:'Explore potentially relevant schemes; discovery does not confirm eligibility.'},
{name:'Ministry of Agriculture & Farmers Welfare',url:'https://agriwelfare.gov.in/',note:'Official ministry information and programme gateway. Check the relevant programme page for current rules.'}],
'MSME Support':[
{name:'Udyam Registration',url:'https://udyamregistration.gov.in/',note:'Official Ministry of MSME registration portal; registration is free.'},
{name:'Ministry of MSME',url:'https://msme.gov.in/',note:'Official ministry information route for MSME programmes and initiatives.'},
{name:'myScheme',url:'https://www.myscheme.gov.in/',note:'Discover schemes, then verify the individual scheme rules and application destination.'}],
'Financial Benefits':[{name:'myScheme',url:'https://www.myscheme.gov.in/',note:'Discover government schemes. A potentially relevant result is not confirmation of eligibility, sanction or payment.'}],
'Registrations/Approvals':[
{name:'National Single Window System',url:'https://www.nsws.gov.in/',note:'Business-approval discovery/application route for participating approvals. Check other relevant government portals where required.'},
{name:'Udyam Registration',url:'https://udyamregistration.gov.in/',note:'Official MSME registration portal where relevant; do not infer tax treatment from Udyam/MSME status.'},
{name:'FoSCoS / FSSAI',url:'https://foscos.fssai.gov.in/',note:'Official food-business licensing/registration system. Verify current category, thresholds, fees and requirements there rather than relying on stored figures.'}],
'Not Sure':[
{name:'myScheme',url:'https://www.myscheme.gov.in/',note:'Broad government-scheme discovery route; verify each scheme before acting.'},
{name:'National Single Window System',url:'https://www.nsws.gov.in/',note:'Business-approval discovery where a business activity is involved; its guidance is not exhaustive legal clearance.'}]
};
function govStart(){const a=document.querySelector<HTMLDivElement>('#app');if(!a)return;a.innerHTML=`<main class="shell"><header><p class="eyebrow">Government Help</p><h1>Choose what you need</h1><p>Select a broad category. Skill Aur Dhandha routes you to official sources; it does not process applications.</p></header><article class="card dropdown-panel"><label>Help category<select id="gov-mode-select"><option value="">Choose an option</option>${govModes.map(x=>`<option value="${x}">${x}</option>`).join('')}</select></label><button class="choice" id="gov-show-routes" type="button">Show official routes<span>›</span></button></article><article class="card"><h2>Before you open a government portal</h2><p><strong>Privacy:</strong> Skill Aur Dhandha does not ask you to submit Aadhaar, PAN, bank details, passwords, OTPs or scheme-application credentials here. Check your own eligibility on the official government destination.</p><p><strong>Local-language help:</strong> where that service is supported through India Post or another authorised government assistance channel, you may ask there for help understanding the published information. The official department/portal remains the authority.</p></article>${gmic()}${gnav('gov-back')}</main>`;}
function govRoutes(){const a=document.querySelector<HTMLDivElement>('#app');if(!a)return;const routes=routeMap[govMode]||routeMap['Not Sure'];a.innerHTML=`<main class="shell"><header><p class="eyebrow">Government Help · ${govMode}</p><h1>Official routes</h1><p>Open the relevant official portal directly. Things to check before proceeding are shown beneath each route.</p></header>${routes.map(r=>`<article class="card"><p class="eyebrow">VERIFIED FACT · official destination</p><h2>${r.name}</h2><p>${r.note}</p><a class="choice" href="${r.url}" target="_blank" rel="noopener noreferrer">Open official portal<span>↗</span></a><p><strong>Things to check before proceeding:</strong> verify current eligibility, documents, fees, deadlines and conditions on the official website. Skill Aur Dhandha does not submit applications, collect documents or guarantee benefits.</p><p><strong>Safety:</strong> do not pay an unofficial agent because a scheme appears here; use the official portal or department contact shown by the authority.</p></article>`).join('')}<article class="card"><h2>Need local-language or offline help?</h2><p>Use the official government portal first. Where the same service is supported through India Post, you may ask your local post office whether assistance is available in your language for understanding the published information. A post office does not decide another department's eligibility, benefit, fee, approval or deadline. The relevant official scheme/department portal remains the authority.</p><a class="choice" href="https://www.indiapost.gov.in/" target="_blank" rel="noopener noreferrer">India Post official website<span>↗</span></a></article><article class="card"><p><strong>Safety:</strong> use the official destination shown here. Do not share passwords or OTPs with anyone claiming to complete the process for you.</p></article>${gmic()}${gnav('gov-routes-back')}</main>`;}
document.addEventListener('click',e=>{const t=e.target as HTMLElement;const launch=t.closest<HTMLButtonElement>('[data-i="4"]');if(launch){e.preventDefault();govStart();return;}if(t.closest('#gov-show-routes')){const select=document.querySelector<HTMLSelectElement>('#gov-mode-select');govMode=(select?.value as typeof govModes[number])||'Not Sure';govRoutes();return;}if(t.closest('#gov-routes-back')){govStart();return;}if(t.closest('#gov-back')||t.closest('#gov-home')){govRoot();return;}});
document.addEventListener('open-government-help',govStart);
