const app=document.querySelector<HTMLDivElement>('#app');
const groups=[
  ['Age group',['17 or under','18–24','25–34','35–49','50–59','60+','Not sure / Skip']],
  ['Gender (optional)',['Woman','Man','Another identity','Prefer not to say / Skip']],
  ['Education / background',['School level','ITI / vocational','Diploma','Graduate or above','Self-taught / practical experience','Not sure / Skip']],
  ['Skills',['Cooking / food','Sales / customer service','Technical / repair','Digital / computer','Creative / making','Teaching / explaining','Not sure / Skip']],
  ['Interests / hobbies',['Food','Retail / trading','Services','Making / manufacturing','Agriculture','Digital / online','Not sure / Skip']],
  ['Investment preference',['Low investment','Moderate investment','Higher investment','Not sure / Skip']],
  ['Time available',['A few hours a week','Part-time','Most days','Full-time','Not sure / Skip']],
  ['Operating location',['From home','Shop / workspace','Mobile / customer location','Online','Not sure / Skip']],
  ['Broad geography',['Village / rural','Small town','City','Pan-India / online','Not sure / Skip']]
] as const;
const categories=['Food','Retail','Service / Skill','Manufacturing','Agriculture / Farm Business','Digital / Online','Home-based'] as const;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const saved=()=>{try{const v=JSON.parse(localStorage.getItem('skill-aur-dhandha-guided-filters')||'{}');return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,string>:{};}catch{return {}}};
const root=()=>{location.href='/';};
const returnToPath=()=>{const pathButton=document.querySelector<HTMLButtonElement>('[data-i="0"]');if(pathButton){pathButton.click();return;}root();};
function saveForm(){const form=document.querySelector<HTMLFormElement>('#guided-filters');if(form)localStorage.setItem('skill-aur-dhandha-guided-filters',JSON.stringify(Object.fromEntries(new FormData(form))));}
function suggestions(profile:Record<string,string>){const scores=new Map<string,number>(categories.map(c=>[c,0]));const add=(c:string,n=1)=>scores.set(c,(scores.get(c)||0)+n);const skill=profile.g3||'',interest=profile.g4||'',investment=profile.g5||'',time=profile.g6||'',place=profile.g7||'',geo=profile.g8||'';if(skill.includes('Cooking')){add('Food',3);add('Home-based',2)}if(skill.includes('Sales')){add('Retail',2);add('Service / Skill',1)}if(skill.includes('Technical'))add('Service / Skill',3);if(skill.includes('Digital'))add('Digital / Online',3);if(skill.includes('Creative')){add('Home-based',2);add('Digital / Online',1);add('Manufacturing',1)}if(skill.includes('Teaching')){add('Service / Skill',3);add('Home-based',2);add('Digital / Online',1)}if(interest==='Food')add('Food',3);if(interest.includes('Retail'))add('Retail',3);if(interest==='Services')add('Service / Skill',3);if(interest.includes('manufacturing'))add('Manufacturing',3);if(interest==='Agriculture')add('Agriculture / Farm Business',3);if(interest.includes('Digital'))add('Digital / Online',3);if(place==='From home')add('Home-based',3);if(place==='Online')add('Digital / Online',3);if(place==='Shop / workspace'){add('Retail',2);add('Manufacturing',1)}if(place==='Mobile / customer location')add('Service / Skill',2);if(investment==='Low investment'){add('Service / Skill',1);add('Digital / Online',1);add('Home-based',1)}if(investment==='Higher investment'){add('Manufacturing',1);add('Retail',1)}if(time==='A few hours a week'||time==='Part-time'){add('Home-based',1);add('Service / Skill',1);add('Digital / Online',1)}if(geo==='Village / rural')add('Agriculture / Farm Business',2);if(geo==='Pan-India / online')add('Digital / Online',2);return [...categories].sort((a,b)=>(scores.get(b)||0)-(scores.get(a)||0)||categories.indexOf(a)-categories.indexOf(b));}
function renderCategories(){if(!app)return;const profile=saved(),ordered=suggestions(profile),hasSignal=Object.values(profile).some(v=>v&&!v.includes('Skip'));app.innerHTML=`<main class="shell"><header><p class="eyebrow">Start a Business</p><h1>Choose a category</h1><p>${hasSignal?'Based on your broad optional filters, the first categories may be worth exploring. This is a transparent fit suggestion, not a score, winner or income prediction.':'No profile signal was required, so all categories remain equally open for exploration.'}</p></header>${hasSignal?`<article class="card"><p><strong>Why this order?</strong> It only uses broad choices such as skill, interest, investment preference, time and operating location saved on this device. It does not infer demand, profit or eligibility.</p></article>`:''}<section class="actions">${ordered.map((x,i)=>`<button class="choice guided-category" data-category="${esc(x)}" type="button">${hasSignal&&i<3?`Suggested · ${x}`:x}<span>›</span></button>`).join('')}</section><article class="card"><p><strong>Privacy:</strong> no name, exact date of birth, Aadhaar, PAN, home address or bank information is requested.</p></article><button class="mic" type="button" aria-label="Voice input"><span aria-hidden="true">●</span> Any Indian language</button><nav class="nav" aria-label="Navigation"><button id="guided-category-back" type="button">← Back</button><button id="guided-category-home" type="button">Home</button></nav></main>`;document.querySelector('#guided-category-back')?.addEventListener('click',renderGuidedFilters);document.querySelector('#guided-category-home')?.addEventListener('click',root);document.querySelectorAll<HTMLButtonElement>('.guided-category').forEach(b=>b.addEventListener('click',()=>{const category=b.dataset.category||'';localStorage.setItem('skill-aur-dhandha-selected-category',category);document.dispatchEvent(new CustomEvent('skill-category-selected',{detail:category}));}));}
function renderGuidedFilters(){if(!app)return;const prior=saved();app.innerHTML=`<main class="shell"><header><p class="eyebrow">Start a Business</p><h1>Optional reality filters</h1><p>Use broad profile choices to narrow exploration. Every question is optional; use Skip whenever you prefer.</p></header><article class="card"><p><strong>Privacy-minimizing profile:</strong> broad bands only. Do not enter your name, exact DOB, address, Aadhaar, PAN or bank information.</p></article><form id="guided-filters">${groups.map(([name,choices],i)=>`<fieldset class="card"><legend><strong>${name}</strong></legend><div class="actions">${choices.map(choice=>`<label class="choice"><input type="radio" name="g${i}" value="${esc(choice)}" ${prior[`g${i}`]===choice?'checked':''}> ${choice}</label>`).join('')}</div></fieldset>`).join('')}<button class="choice" id="guided-next" type="button">Choose business category<span>›</span></button></form><button class="mic" type="button" aria-label="Voice input"><span aria-hidden="true">●</span> Any Indian language</button><nav class="nav" aria-label="Navigation"><button id="guided-back" type="button">← Back</button><button id="guided-home" type="button">Home</button></nav></main>`;document.querySelector('#guided-back')?.addEventListener('click',returnToPath);document.querySelector('#guided-home')?.addEventListener('click',root);document.querySelector('#guided-next')?.addEventListener('click',()=>{saveForm();renderCategories();});}
document.addEventListener('click',(event)=>{const target=event.target as HTMLElement|null;const b=target?.closest<HTMLButtonElement>('[data-p="2"]');if(!b)return;queueMicrotask(renderGuidedFilters);});