const app=document.querySelector<HTMLDivElement>('#app');
const groups=[
  ['Investment preference',['Low investment','Moderate investment','Higher investment','Not sure / Skip']],
  ['Time available',['A few hours a week','Part-time','Most days','Full-time','Not sure / Skip']],
  ['Operating location',['From home','Shop / workspace','Mobile / customer location','Online','Not sure / Skip']],
  ['Broad geography',['Village / rural','Small town','City','Pan-India / online','Not sure / Skip']]
] as const;
const categories=['Food','Retail','Service / Skill','Manufacturing','Agriculture / Farm Business','Digital / Online','Home-based'];
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]||c));
const saved=()=>{try{const v=JSON.parse(localStorage.getItem('skill-aur-dhandha-guided-filters')||'{}');return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,string>:{};}catch{return {}}};
function saveForm(){const form=document.querySelector<HTMLFormElement>('#guided-filters');if(form)localStorage.setItem('skill-aur-dhandha-guided-filters',JSON.stringify(Object.fromEntries(new FormData(form))));}
function renderCategories(){if(!app)return;app.innerHTML=`<main class="shell"><header><p class="eyebrow">Start a Business</p><h1>Choose a category</h1><p>Your optional filters are saved on this device. Choose a broad category to explore; no result is guaranteed.</p></header><section class="actions">${categories.map(x=>`<button class="choice guided-category" data-category="${esc(x)}" type="button">${x}<span>›</span></button>`).join('')}</section><button class="mic" type="button" aria-label="Voice input"><span aria-hidden="true">●</span> Any Indian language</button><nav class="nav" aria-label="Navigation"><button id="guided-category-back" type="button">← Back</button><button id="guided-category-home" type="button">Home</button></nav></main>`;document.querySelector('#guided-category-back')?.addEventListener('click',renderGuidedFilters);document.querySelector('#guided-category-home')?.addEventListener('click',()=>{location.href='/';});document.querySelectorAll<HTMLButtonElement>('.guided-category').forEach(b=>b.addEventListener('click',()=>{const category=b.dataset.category||'';localStorage.setItem('skill-aur-dhandha-selected-category',category);document.dispatchEvent(new CustomEvent('skill-category-selected',{detail:category}));}));}
function renderGuidedFilters(){if(!app)return;const prior=saved();app.innerHTML=`<main class="shell"><header><p class="eyebrow">Start a Business</p><h1>Optional reality filters</h1><p>Tap what fits. Every question is optional; choose Not sure / Skip whenever you prefer.</p></header><form id="guided-filters">${groups.map(([name,choices],i)=>`<fieldset class="card"><legend><strong>${name}</strong></legend><div class="actions">${choices.map(choice=>`<label class="choice"><input type="radio" name="g${i}" value="${esc(choice)}" ${prior[`g${i}`]===choice?'checked':''}> ${choice}</label>`).join('')}</div></fieldset>`).join('')}<button class="choice" id="guided-next" type="button">Choose business category<span>›</span></button></form><button class="mic" type="button" aria-label="Voice input"><span aria-hidden="true">●</span> Any Indian language</button><nav class="nav" aria-label="Navigation"><button id="guided-back" type="button">← Back</button><button id="guided-home" type="button">Home</button></nav></main>`;document.querySelector('#guided-back')?.addEventListener('click',()=>history.back());document.querySelector('#guided-home')?.addEventListener('click',()=>{location.href='/';});document.querySelector('#guided-next')?.addEventListener('click',()=>{saveForm();renderCategories();});}
document.addEventListener('click',(event)=>{const target=event.target as HTMLElement|null;const b=target?.closest<HTMLButtonElement>('[data-p="2"]');if(!b)return;queueMicrotask(renderGuidedFilters);});