const learnModes=['Learn a Skill','Improve My Skill','Business Knowledge','Farming Knowledge','Digital/AI Skills','Find Courses'] as const;
let learnMode='Learn a Skill';let learnTopic='';
const lmic=()=>`<button class="mic" type="button" aria-label="Voice input"><span aria-hidden="true">●</span> Any Indian language</button>`;
const lnav=(backId:string)=>`<nav class="nav" aria-label="Navigation"><button id="${backId}" type="button">← Back</button><button id="learn-home" type="button">Home</button></nav>`;
const learnRoot=()=>{location.href='/';};
const topics:Record<string,string[]>={
'Learn a Skill':['Communication','Digital basics','Sales & customer service','Food & hospitality','Repair & technical skills','Office productivity','Bookkeeping basics','Tailoring & alterations','Beauty & personal service','Photography basics','Video editing basics','Graphic design basics','Spreadsheets & data','Language & translation','Home-service skills'],
'Improve My Skill':['Practice plan','Quality & consistency','Customer communication','Digital tools','Pricing your work','Portfolio & proof of work','Time management','Problem solving','Negotiation basics','Service recovery','Workplace communication','Documentation habits','Safety & quality checks','Customer follow-up','Train another person'],
'Business Knowledge':['Customer discovery','Pricing & costs','Sales basics','Cash-flow basics','Operations','Digital marketing','Bookkeeping basics','Inventory basics','Supplier selection','Packaging & branding','Distribution channels','Customer retention','Break-even basics','Hiring basics','Business compliance awareness'],
'Farming Knowledge':['Crop planning','Post-harvest handling','Market awareness','Farm records','Value addition','Digital agriculture','Nursery basics','Soil & input planning','Water-use planning','Farm equipment economics','Grading & packing','Storage basics','Direct-market routes','Farmer-group awareness','Seasonal risk planning'],
'Digital/AI Skills':['Digital basics','Online safety','AI basics','Prompting & verification','Spreadsheets & data','Digital marketing','Document productivity','Presentation design','Online research','Email & collaboration','Website basics','Catalogue creation','Social media operations','Video editing basics','Data-cleaning basics'],
'Find Courses':['Skill training','Business learning','Farming learning','Digital/AI learning','Technical learning','General learning','Communication training','Office productivity','Sales training','Food & hospitality training','Repair training','Design & media learning','Bookkeeping learning','Entrepreneurship learning','Language learning']};
type Guide=[string,string,string];
const generic:Guide=['Define the exact outcome and starting level before choosing learning.','Practise a small observable task with appropriate tools and safety controls.','Verify current prerequisites, provider claims and real-world requirements before spending money.'];
const guides:Record<string,Guide>={
'AI basics':['Use AI for drafts, exploration and assistance, not unquestioned truth.','Practise with non-sensitive information and verify important outputs.','Do not paste confidential or sensitive data into tools without understanding data handling.'],
'Prompting & verification':['State the task, context, constraints and output format clearly.','Ask for assumptions and sources where facts matter.','Check important claims against primary or authoritative sources.'],
'Digital/AI learning':['Start with a practical task and safety basics.','Practise with non-sensitive data.','Verify changing tool features on current official documentation.'],
'Online safety':['Use strong unique passwords and recovery controls.','Never share OTPs or credentials.','Verify links and providers before payments or document uploads.'],
'Digital marketing':['Define audience and objective before choosing a channel.','Measure useful actions such as qualified enquiries or sales.','Do not assume followers, views or clicks guarantee revenue.'],
'Video editing basics':['Learn timeline, cuts, audio levels, captions and export settings.','Practise with footage, music and assets you own or are licensed to use.','Keep source/project files organised and test exports on target devices.'],
'Repair & technical skills':['Learn safety and tool basics before live work.','Practise on low-risk training tasks before customer equipment.','Use recognised training where electrical, mechanical or safety risk is involved.'],
'Food & hospitality':['Start with hygiene, consistency and safe handling.','Practise a repeatable preparation or service checklist.','Check current official food-safety requirements before commercial activity.'],
'Pricing & costs':['Separate variable, fixed and one-time costs.','Calculate contribution and break-even using your own numbers.','Stress-test price and cost changes before committing money.'],
'Customer discovery':['Define who may need the offer and what problem it solves.','Speak to several potential customers before assuming demand.','Record patterns without collecting unnecessary personal data.'],
'Business compliance awareness':['Identify business form, activity, location and turnover facts that can affect requirements.','Use current official portals for registrations, tax and sector rules.','Do not assume MSME status alone determines tax, licences or eligibility.'],
'Farming learning':['Choose content relevant to crop, geography and season.','Prefer official agricultural institutions for advisories.','Validate general learning against local conditions.'],
'Skill training':['Define the skill and level you need before searching.','Compare curriculum, duration, language, delivery mode and any fees.','Verify provider and certificate claims on the destination itself.']};
const guideFor=(topic:string):Guide=>guides[topic]||generic;
function learnHome(){const a=document.querySelector<HTMLDivElement>('#app');if(!a)return;a.innerHTML=`<main class="shell"><header><p class="eyebrow">Learn & Grow</p><h1>What do you want to learn?</h1><p>Choose a learning genre. Skill Aur Dhandha guides you; it does not run a course marketplace.</p></header><article class="card dropdown-panel"><label>Learning genre<select id="learn-mode-select"><option value="">Choose an option</option>${learnModes.map(x=>`<option value="${x}">${x}</option>`).join('')}</select></label><button class="choice" id="learn-mode-go" type="button">Continue<span>›</span></button></article><article class="card"><h2>AI & future-work shortcuts</h2><button class="choice" id="learn-ai-direct" type="button">AI courses & practical learning paths<span>›</span></button><button class="choice" id="learn-future-direct" type="button">5–10 year career directions with strong earning potential<span>›</span></button><p>Career directions are not salary rankings or guarantees. Compare skills, qualifications, current vacancies and real compensation evidence before choosing training.</p></article><article class="card"><p>No provider accounts, purchases, ratings or enrollment are handled inside this app.</p></article>${lmic()}${lnav('learn-back')}</main>`;}
function topicSelect(){const a=document.querySelector<HTMLDivElement>('#app');if(!a)return;const list=topics[learnMode]||topics['Learn a Skill'];a.innerHTML=`<main class="shell"><header><p class="eyebrow">Learn & Grow · ${learnMode}</p><h1>Choose from ${list.length} learning options</h1></header><article class="card dropdown-panel"><label>Topic<select id="learn-topic-select"><option value="">Choose an option</option>${list.map(x=>`<option value="${x}">${x}</option>`).join('')}<option value="custom">Other / type my topic</option></select></label><label id="learn-custom-wrap" hidden>My topic<input id="learn-custom-topic" maxlength="80"></label><button class="choice" id="learn-topic-go" type="button">Needs & Requirements<span>›</span></button></article>${learnMode==='Digital/AI Skills'||learnMode==='Find Courses'?`<article class="card"><button class="choice" id="learn-ai-direct" type="button">Open dedicated AI learning navigator<span>›</span></button><button class="choice" id="learn-future-direct" type="button">Explore future career directions<span>›</span></button></article>`:''}${lmic()}${lnav('learn-topics-back')}</main>`;}
function knowledge(){const a=document.querySelector<HTMLDivElement>('#app');if(!a)return;const c=guideFor(learnTopic);a.innerHTML=`<main class="shell"><header><p class="eyebrow">Learn & Grow · ${learnTopic}</p><h1>Needs & Requirements</h1></header><article class="card needs-panel"><ol>${c.map(x=>`<li>${x}</li>`).join('')}</ol></article><article class="card research-panel"><h2>Pan-India research lens</h2><p>Check how this skill is used across sectors and regions, the practical level employers/customers may expect, language or tool requirements, delivery mode, current training routes and changing technology.</p><p><strong>Research standard:</strong> prefer current government, recognised training institutions, sector bodies and primary provider information. Do not treat an old course page or salary example as a guaranteed outcome.</p></article><button class="choice" id="learn-roadmap">Build a Practice Roadmap<span>›</span></button><button class="choice" id="where-learn">Official / trusted learning routes<span>›</span></button>${/AI|Prompting/i.test(learnTopic)?`<button class="choice" id="learn-ai-direct">Dedicated AI learning navigator<span>›</span></button>`:''}${lmic()}${lnav('learn-knowledge-back')}</main>`;}
function roadmap(){const a=document.querySelector<HTMLDivElement>('#app');if(!a)return;const c=guideFor(learnTopic);a.innerHTML=`<main class="shell"><header><p class="eyebrow">Learn & Grow · ${learnTopic}</p><h1>5-step practice roadmap</h1></header><article class="card"><ol><li>Define one observable outcome.</li><li>${c[0]}</li><li>${c[1]}</li><li>Create proof you have the right to retain/share.</li><li>${c[2]}</li></ol></article><button class="choice" id="roadmap-learn">Official / trusted learning routes<span>›</span></button>${lmic()}${lnav('learn-roadmap-back')}</main>`;}
function gateways(){const a=document.querySelector<HTMLDivElement>('#app');if(!a)return;a.innerHTML=`<main class="shell"><header><p class="eyebrow">Learn & Grow · ${learnTopic}</p><h1>Official / trusted routes</h1></header><article class="card"><h2>Skill India Digital / DGT</h2><a class="choice" href="https://dgt.skillindiadigital.gov.in/" target="_blank" rel="noopener noreferrer">Open official portal<span>↗</span></a></article><article class="card"><h2>SWAYAM</h2><a class="choice" href="https://swayam.gov.in/" target="_blank" rel="noopener noreferrer">Open official portal<span>↗</span></a></article><article class="card"><p><strong>Caution:</strong> verify current prerequisites, curriculum, fees and certificate terms. Skill Aur Dhandha does not enroll users or guarantee certification, employment or income.</p></article>${lmic()}${lnav('learn-gateways-back')}</main>`;}
document.addEventListener('click',e=>{const t=e.target as HTMLElement;const launch=t.closest<HTMLButtonElement>('[data-i="3"]');if(launch){e.preventDefault();learnHome();return;}if(t.closest('#learn-ai-direct')){document.dispatchEvent(new Event('open-ai-learning'));return;}if(t.closest('#learn-future-direct')){document.dispatchEvent(new Event('open-future-careers'));return;}if(t.closest('#learn-mode-go')){const s=document.querySelector<HTMLSelectElement>('#learn-mode-select');learnMode=(s?.value as typeof learnModes[number])||'Learn a Skill';topicSelect();return;}if(t.closest('#learn-topic-go')){const s=document.querySelector<HTMLSelectElement>('#learn-topic-select'),custom=document.querySelector<HTMLInputElement>('#learn-custom-topic');learnTopic=s?.value==='custom'?(custom?.value.trim()||'General learning'):(s?.value||'General learning');knowledge();return;}if(t.closest('#learn-roadmap')){roadmap();return;}if(t.closest('#roadmap-learn')||t.closest('#where-learn')){gateways();return;}if(t.closest('#learn-gateways-back')||t.closest('#learn-roadmap-back')){knowledge();return;}if(t.closest('#learn-knowledge-back')){topicSelect();return;}if(t.closest('#learn-topics-back')){learnHome();return;}if(t.closest('#learn-back')||t.closest('#learn-home')){learnRoot();return;}});
document.addEventListener('change',e=>{const t=e.target as HTMLSelectElement;if(t.id==='learn-topic-select'){const w=document.querySelector<HTMLElement>('#learn-custom-wrap');if(w)w.hidden=t.value!=='custom';}});
document.addEventListener('open-learn',learnHome);
export {learnHome};