const dimensions=[
['Current market share / size','Use a current credible source for the exact product, service or genre. Distinguish total market size from a company/brand market-share percentage. If no reliable India-specific figure is available, show “Not verified / not published” rather than inventing a number.'],
['Future predicted share / size','Use a dated forecast from a credible research, government or recognised sector source. State the forecast horizon and whether it refers to India, a region or global market. Do not present a global forecast as an India forecast.'],
['CAGR','Show CAGR only when the source states a start year, end year, geography and market definition. Never infer a precise CAGR from unrelated figures or mixed definitions.'],
['Growth perspective','Explain demand drivers, adoption, customer behaviour, technology, policy/infrastructure, distribution and constraints. Separate VERIFIED FACT from GUIDANCE and avoid guaranteed-growth language.'],
['Competition','Describe direct competitors, substitutes, local/unorganised competition, digital/platform competition, entry barriers and likely differentiation. Do not declare a winner or fabricate competitor market shares.']
] as const;
function context(){const main=document.querySelector<HTMLElement>('#app main');if(!main)return'';return [main.querySelector('.eyebrow')?.textContent?.trim(),main.querySelector('h1')?.textContent?.trim()].filter(Boolean).join(' · ');}
function inject(){const main=document.querySelector<HTMLElement>('#app main');if(!main)return;for(const panel of [...main.querySelectorAll<HTMLElement>('.research-panel')]){if(panel.querySelector('[data-universal-research-lens]'))continue;const box=document.createElement('div');box.dataset.universalResearchLens='true';box.innerHTML=`<h3>Market Research Checklist</h3><p><strong>Applies to:</strong> ${context()||'this opportunity / genre'}</p><div class="table-wrap"><table><thead><tr><th>Research dimension</th><th>Evidence rule</th></tr></thead><tbody>${dimensions.map(([name,rule])=>`<tr><th>${name}</th><td>${rule}</td></tr>`).join('')}</tbody></table></div><p><strong>Evidence labels:</strong> VERIFIED FACT · YOUR CALCULATION · ESTIMATE-SCENARIO · GUIDANCE.</p>`;panel.append(box);}}
const observer=new MutationObserver(()=>queueMicrotask(inject));observer.observe(document.documentElement,{subtree:true,childList:true});queueMicrotask(inject);
export {dimensions};
