type TiffinData = Record<string,string>;
const app=document.querySelector<HTMLDivElement>('#app');
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const mic=()=>`<button class="mic" type="button" aria-label="Voice input"><span aria-hidden="true">●</span> Any Indian language</button>`;
const nav=()=>`<nav class="nav" aria-label="Navigation"><button id="s13j-back" type="button">← Back</button><button id="s13j-home" type="button">Home</button></nav>`;
const safeData=():TiffinData=>{try{const v=JSON.parse(localStorage.getItem('skill-aur-dhandha-home-tiffin-simulator')||'{}');return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}catch{return {}}};
function wire(back?:()=>void){document.querySelector('#s13j-back')?.addEventListener('click',back||(()=>location.href='/'));document.querySelector('#s13j-home')?.addEventListener('click',()=>{location.href='/';});}
function evidence(){if(!app)return;app.innerHTML=`<main class="shell"><header><p class="eyebrow">Home Tiffin</p><h1>Evidence Snapshot</h1><p>VERIFIED FACT — sector context, not a guarantee of demand or profit for an individual tiffin business.</p></header><article class="card"><h2>Registered food-processing sector GVA</h2><p>₹91,667.66 crore (2014-15) → ₹187,712.60 crore (2022-23).</p><p><strong>Source:</strong> Ministry of Food Processing Industries, Annual Report 2024-25. <strong>Reference:</strong> 2014-15 to 2022-23. <strong>Verified:</strong> 17 Sep 2026.</p><p><strong>Limitation:</strong> This registered-sector evidence does not measure home-tiffin demand, revenue or profitability.</p></article><article class="card"><h2>Food-business regulatory context</h2><p>Food-business licensing or registration requirements apply; check the current official route for your setup.</p><div class="actions"><a class="choice" href="https://www.mofpi.gov.in/documents/reports/annual-report" target="_blank" rel="noopener noreferrer">View MoFPI source<span>›</span></a><a class="choice" href="https://foscos.fssai.gov.in/" target="_blank" rel="noopener noreferrer">View FSSAI / FoSCoS<span>›</span></a></div></article><button class="choice" id="s13j-journey" type="button">5-Step Decision Journey<span>›</span></button>${mic()}${nav()}</main>`;wire();document.querySelector('#s13j-journey')?.addEventListener('click',()=>journey(0));}
const steps=[
 {title:'Decide your customer and meal type',body:'Choose a narrow starting customer such as nearby office workers, students or households, then define meal timing and whether you will offer lunch, dinner or both. Keep the first menu small enough to produce consistently. Do not assume demand: speak to potential customers or run a small preorder test.'},
 {title:'Decide menu and unit economics',body:'List each meal component and calculate ingredients, packaging, fuel/electricity, wastage and any delivery cost. Compare the total variable cost with the proposed selling price. Use your own supplier prices rather than copied internet estimates. Keep a buffer for price changes and rejected or unsold meals.'},
 {title:'Decide operating setup',body:'Check kitchen capacity, storage, hygiene workflow, preparation time and how many meals you can safely produce without reducing quality. If rent, extra equipment or gas installation is needed, include it before committing. Check current food-business registration or licensing requirements through FSSAI/FoSCoS.'},
 {title:'Decide delivery and order method',body:'Compare self-pickup, your own local delivery and third-party delivery where available. Verify current platform or delivery charges directly before using them in calculations. Decide how orders will be confirmed without building a buyer-seller marketplace inside Skill Aur Dhandha.'},
 {title:'Decide investment and low-risk pilot',body:'Total the equipment/startup amount and one month of expected operating costs. Run the simulator with conservative assumptions, then test a small batch or limited preorder period before expanding. Record repeat orders, wastage, preparation time and actual margin. Expand only after your own evidence supports it.'}
];
function journey(i:number){if(!app)return;const step=steps[Math.max(0,Math.min(i,steps.length-1))];app.innerHTML=`<main class="shell"><header><p class="eyebrow">Home Tiffin · Step ${i+1} of ${steps.length}</p><h1>${step.title}</h1></header><article class="card"><p>${step.body}</p><p><strong>GUIDANCE:</strong> validate local facts and current requirements before spending money.</p></article>${i<steps.length-1?`<button class="choice" id="s13j-next" type="button">Next step<span>›</span></button>`:`<button class="choice" id="s13j-ready" type="button">Ready to test the numbers<span>›</span></button>`}${mic()}${nav()}</main>`;wire(()=>i>0?journey(i-1):evidence());document.querySelector('#s13j-next')?.addEventListener('click',()=>journey(i+1));document.querySelector('#s13j-ready')?.addEventListener('click',simulator);}
function simulator(){if(!app)return;const d:TiffinData={price:'100',meals:'25',days:'26',ingredients:'40',packaging:'8',delivery:'0',fixed:'5000'},s=safeData(),v=(k:string)=>s[k]??d[k];app.innerHTML=`<main class="shell"><header><p class="eyebrow">Home Tiffin</p><h1>Business Simulator</h1><p>SCENARIO — editable starting assumptions, not verified market prices or an income promise.</p></header><form class="card" id="s13j-sim"><label>Selling price per meal (₹)<input type="number" min="0" name="price" value="${v('price')}"></label><label>Meals sold per day<input type="number" min="0" name="meals" value="${v('meals')}"></label><label>Operating days per month<input type="number" min="0" max="31" name="days" value="${v('days')}"></label><label>Ingredients per meal (₹)<input type="number" min="0" name="ingredients" value="${v('ingredients')}"></label><label>Packaging per meal (₹)<input type="number" min="0" name="packaging" value="${v('packaging')}"></label><label>Delivery/platform cost per meal (₹)<input type="number" min="0" name="delivery" value="${v('delivery')}"></label><label>Other monthly fixed costs (₹)<input type="number" min="0" name="fixed" value="${v('fixed')}"></label><button class="choice" id="s13j-save" type="button">Save scenario<span>›</span></button></form>${mic()}${nav()}</main>`;wire(()=>journey(steps.length-1));document.querySelector('#s13j-save')?.addEventListener('click',()=>{const f=document.querySelector<HTMLFormElement>('#s13j-sim');if(!f)return;localStorage.setItem('skill-aur-dhandha-home-tiffin-simulator',JSON.stringify(Object.fromEntries(new FormData(f))));const b=document.querySelector<HTMLButtonElement>('#s13j-save');if(b)b.textContent='Saved ✓';});}
document.addEventListener('skill-route',(event)=>{const route=(event as CustomEvent<string>).detail;if(route==='evidence')evidence();if(route==='simulator')simulator();});