type TiffinData = Record<string,string>;
const app=document.querySelector<HTMLDivElement>('#app');
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const mic=()=>`<button class="mic" type="button" aria-label="Voice input"><span aria-hidden="true">●</span> Any Indian language</button>`;
const nav=()=>`<nav class="nav" aria-label="Navigation"><button id="s13j-back" type="button">← Back</button><button id="s13j-home" type="button">Home</button></nav>`;
const safeData=():TiffinData=>{try{return JSON.parse(localStorage.getItem('skill-aur-dhandha-home-tiffin-simulator')||'{}')}catch{return {}}};
function wire(){document.querySelector('#s13j-back')?.addEventListener('click',()=>history.back());document.querySelector('#s13j-home')?.addEventListener('click',()=>{location.href='/';});}
function evidence(){if(!app)return;app.innerHTML=`<main class="shell"><header><p class="eyebrow">Home Tiffin</p><h1>Evidence Snapshot</h1><p>VERIFIED FACT — sector context, not a guarantee of demand or profit for an individual tiffin business.</p></header><article class="card"><h2>Registered food-processing sector GVA</h2><p>₹91,667.66 crore (2014-15) → ₹187,712.60 crore (2022-23).</p><p><strong>Source:</strong> Ministry of Food Processing Industries, Annual Report 2024-25. <strong>Reference:</strong> 2014-15 to 2022-23. <strong>Verified:</strong> 17 Sep 2026.</p><p><strong>Limitation:</strong> This registered-sector evidence does not measure home-tiffin demand, revenue or profitability.</p></article><article class="card"><h2>Food-business regulatory context</h2><p>Food-business licensing or registration requirements apply; check the current official route for your setup.</p><div class="actions"><a class="choice" href="https://www.mofpi.gov.in/documents/reports/annual-report" target="_blank" rel="noopener noreferrer">View MoFPI source<span>›</span></a><a class="choice" href="https://foscos.fssai.gov.in/" target="_blank" rel="noopener noreferrer">View FSSAI / FoSCoS<span>›</span></a></div></article>${mic()}${nav()}</main>`;wire();}
function simulator(){if(!app)return;const d:TiffinData={price:'100',meals:'25',days:'26',ingredients:'40',packaging:'8',delivery:'0',fixed:'5000'},s=safeData(),v=(k:string)=>s[k]??d[k];app.innerHTML=`<main class="shell"><header><p class="eyebrow">Home Tiffin</p><h1>Business Simulator</h1><p>SCENARIO — editable starting assumptions, not verified market prices or an income promise.</p></header><form class="card" id="s13j-sim"><label>Selling price per meal (₹)<input type="number" min="0" name="price" value="${v('price')}"></label><label>Meals sold per day<input type="number" min="0" name="meals" value="${v('meals')}"></label><label>Operating days per month<input type="number" min="0" max="31" name="days" value="${v('days')}"></label><label>Ingredients per meal (₹)<input type="number" min="0" name="ingredients" value="${v('ingredients')}"></label><label>Packaging per meal (₹)<input type="number" min="0" name="packaging" value="${v('packaging')}"></label><label>Delivery/platform cost per meal (₹)<input type="number" min="0" name="delivery" value="${v('delivery')}"></label><label>Other monthly fixed costs (₹)<input type="number" min="0" name="fixed" value="${v('fixed')}"></label><button class="choice" id="s13j-save" type="button">Save scenario<span>›</span></button></form>${mic()}${nav()}</main>`;wire();document.querySelector('#s13j-save')?.addEventListener('click',()=>{const f=document.querySelector<HTMLFormElement>('#s13j-sim');if(!f)return;localStorage.setItem('skill-aur-dhandha-home-tiffin-simulator',JSON.stringify(Object.fromEntries(new FormData(f))));const b=document.querySelector<HTMLButtonElement>('#s13j-save');if(b)b.textContent='Saved ✓';});}
document.addEventListener('skill-route',(event)=>{const route=(event as CustomEvent<string>).detail;if(route==='evidence')evidence();if(route==='simulator')simulator();});
