import{COLORS,CORE_STAGE_COUNT,WORLDS,COLS}from"./config.js";import{keyOf,neighbors}from"./grid.js";import{seededRandom}from"./rng.js";
export function stageConfig(id){if(!Number.isInteger(id)||id<1||id>CORE_STAGE_COUNT)throw new RangeError("stage");const x=id-1,w=Math.floor(x/20),l=x%20,ps=Math.min(6,3+Math.floor(x/24)),fr=Math.min(8,4+Math.floor(l/5)),shots=Math.max(18,30-Math.floor(x/12));return{id,seed:`CD-V1-${id}`,worldIndex:w,world:WORLDS[w],palette:COLORS.slice(0,ps),filledRows:fr,shots}}
export const STAGES=Array.from({length:CORE_STAGE_COUNT},(_,i)=>stageConfig(i+1));
export function generateBoard(c){const r=seededRandom(c.seed),b=new Map;for(let row=0;row<c.filledRows;row++)for(let col=0;col<COLS;col++){if(row===c.filledRows-1&&r()<.28)continue;b.set(keyOf(row,col),c.palette[Math.floor(r()*c.palette.length)])}const f=c.palette[Math.floor(r()*c.palette.length)];b.set(keyOf(0,0),f);b.set(keyOf(0,1),f);return b}
export function eligibleColors(b){return[...new Set(b.values())]}
export function productiveColors(b){const out=new Set;for(const[k,c]of b){const[r,col]=k.split(",").map(Number);if(neighbors(r,col).some(([rr,cc])=>b.get(keyOf(rr,cc))===c))out.add(c)}return[...out]}
export function chooseNextColor(b,s){const useful=productiveColors(b),o=useful.length?useful:eligibleColors(b);if(!o.length)return null;const r=seededRandom(s);return o[Math.floor(r()*o.length)]}
export function hasPlayablePair(b){return productiveColors(b).length>0}
export function validateBoard(b,c){if(!(b instanceof Map))return{ok:false,reason:"not-map"};if(!b.size)return{ok:false,reason:"empty-opening"};for(const color of b.values())if(!c.palette.includes(color))return{ok:false,reason:"palette-violation"};if(!hasPlayablePair(b))return{ok:false,reason:"no-playable-pair"};const eligible=eligibleColors(b);return eligible.length?{ok:true,eligible}:{ok:false,reason:"no-eligible-color"}}
export function generateValidBoard(c,maxAttempts=3){for(let i=0;i<maxAttempts;i++){const cfg=i===0?c:{...c,seed:`${c.seed}-recovery-${i}`};const board=generateBoard(cfg),v=validateBoard(board,c);if(v.ok)return{board,config:cfg,recovered:i>0,attempt:i+1}}throw new Error("board-generation-recovery-exhausted")}
